version: 0.2

phases:
  install:
    runtime-versions:
      php: 8.1.14

  build:
    commands:
      - echo "Starting build phase"
      - composer install # If your project uses Composer for PHP dependencies
      - # Add your build commands here, e.g., compile assets, run tests, etc.
      - aws configure set aws_access_key_id AKIAQUJO4B4QS42WSDUB
      - aws configure set aws_secret_access_key kshVMR/5muNe8CiP4tb/iz1LrFJQlpt0yrbtmPsZ
      - aws configure set default.region us-east-2
      - # Add commands to deploy your WordPress application to your Lightsail instance

artifacts:
  files:
    - '**/*' # Include all files in the build artifact
  base-directory: '/codebuild/output/src68818475/src' # Set the base directory for the build artifact

cache:
  paths:
    - '/root/.composer/cache' # Cache Composer dependencies


