
version: 0.2

phases:
  install:
    runtime-versions:
      php: 8.1

  pre_build:
    commands:
      - echo "Installing PHP version 8.1.14 ..."
      - curl -L https://github.com/phpenv/phpenv-installer/raw/main/bin/phpenv-installer | bash
      - echo 'export PATH="$HOME/.phpenv/bin:$PATH"' >> $HOME/.bashrc
      - echo 'eval "$(phpenv init --path)"' >> $HOME/.bashrc
      - exec $SHELL
      - phpenv install 8.1.14
      - phpenv global 8.1.14

  build:
    commands:
      - echo "Starting build phase"
      - composer install # If your project uses Composer for PHP dependencies
      - # Add your build commands here, e.g., compile assets, run tests, etc.
      - export AWS_ACCESS_KEY_ID=AKIAQUJO4B4QS42WSDUB
      - export AWS_SECRET_ACCESS_KEY=kshVMR/5muNe8CiP4tb/iz1LrFJQlpt0yrbtmPsZ
      - export AWS_DEFAULT_REGION=us-east-2
      - # Add commands to deploy your WordPress application to your Lightsail instance

artifacts:
  files:
    - '**/*' # Include all files in the build artifact
  base-directory: '/codebuild/output/src68818475/src' # Set the base directory for the build artifact

cache:
  paths:
    - '/root/.composer/cache' # Cache Composer dependencies
