
version: 0.2

phases:
  install:
    runtime-versions:
      php: 8.1

  pre_build:
    commands:
      - echo "Installing PHP version 8.1 ..."



  build:
    commands:
      - echo "Starting build phase"
      - # Add your build commands here, e.g., compile assets, run tests, etc.
      - export AWS_ACCESS_KEY_ID=AKIAQUJO4B4QS42WSDUB
      - export AWS_SECRET_ACCESS_KEY=kshVMR/5muNe8CiP4tb/iz1LrFJQlpt0yrbtmPsZ
      - export AWS_DEFAULT_REGION=us-east-2
      - # Add commands to deploy your WordPress application to your Lightsail instance

artifacts:
  files:
    - '**/*' # Include all files in the build artifact
  base-directory: '.'




