
version: 0.2

phases:
  install:
    runtime-versions:
      php: 8.1

  pre_build:
    commands:
      - echo "Starting build phase"
      - composer install # If your project uses Composer for PHP dependencies
      - # Add your build commands here, e.g., compile assets, run tests, etc.
      - export AWS_ACCESS_KEY_ID=AKIAQU56JO4B4QS242WSDUB
      - export AWS_SECRET_ACCESS_KEY=kshVMR/5muNeh8CiP4tb/iz1LghrFJQlpt0yrbtmPst6Z
      - export AWS_DEFAULT_REGION=us-east-2

  build:
    commands:
      - echo "Starting build phase"
      - composer install # If your project uses Composer for PHP dependencies
      - # Add your build commands here, e.g., compile assets, run tests, etc.
      - export AWS_ACCESS_KEY_ID=AKIAQUJO4B4QS42WSDUB
      - export AWS_SECRET_ACCESS_KEY=kshVMR/5muNe8CiP4tb/iz1LrFJQlpt0yrbtmPsZ
      - export AWS_DEFAULT_REGION=us-east-2
      - # Add commands to deploy your WordPress application to your Lightsail instance

artifacts:
  files:
    - '**/*' # Include all files in the build artifact
  base-directory: '/codebuild/output/src68818475/src' # Set the base directory for the build artifact

cache:
  paths:
    - '/root/.composer/cache' # Cache Composer dependencies


